-- Login/authentication schema for the Kang app.
-- Based on the existing kang user/auth tables in the reference PostgreSQL DB.
-- Target: PostgreSQL 11+

CREATE SCHEMA IF NOT EXISTS kang;

CREATE OR REPLACE FUNCTION kang.ms_generate_uuid()
RETURNS uuid
LANGUAGE sql
AS $function$
    SELECT md5(random()::text || clock_timestamp()::text || txid_current()::text)::uuid;
$function$;

CREATE OR REPLACE FUNCTION kang.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE n.nspname = 'kang'
          AND t.typname = 'user_status'
    ) THEN
        CREATE TYPE kang.user_status AS ENUM ('active', 'suspended', 'deleted');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS kang.users (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    firebase_uid text NOT NULL,
    email text,
    email_verified boolean DEFAULT false NOT NULL,
    display_name text,
    photo_url text,
    status kang.user_status DEFAULT 'active'::kang.user_status NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    user_no bigint GENERATED BY DEFAULT AS IDENTITY,
    login_id character varying(100),
    password_hash text,
    user_name character varying(100) DEFAULT ''::character varying NOT NULL,
    user_type character varying(30) DEFAULT 'member'::character varying NOT NULL,
    auth_provider character varying(30) DEFAULT 'firebase'::character varying NOT NULL,
    mfa_enabled boolean DEFAULT false NOT NULL,
    locked_at timestamp with time zone,
    is_active boolean DEFAULT true NOT NULL,
    created_by uuid,
    updated_by uuid,
    deleted_by uuid,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_firebase_uid_key UNIQUE (firebase_uid),
    CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES kang.users(id),
    CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES kang.users(id),
    CONSTRAINT fk_users_deleted_by FOREIGN KEY (deleted_by) REFERENCES kang.users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_user_no
    ON kang.users USING btree (user_no);

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_not_deleted
    ON kang.users USING btree (lower(email))
    WHERE email IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id_not_deleted
    ON kang.users USING btree (lower((login_id)::text))
    WHERE login_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_users_provider
    ON kang.users USING btree (auth_provider);

CREATE INDEX IF NOT EXISTS ix_users_type_active
    ON kang.users USING btree (user_type, is_active);

COMMENT ON COLUMN kang.users.user_no IS 'Sequential user number for admin screens and logs.';
COMMENT ON COLUMN kang.users.login_id IS 'Login ID for local login or admin search. Separate from Firebase UID.';
COMMENT ON COLUMN kang.users.password_hash IS 'Password hash for future local auth. NULL for Firebase-only users.';
COMMENT ON COLUMN kang.users.user_name IS 'User name used in admin screens and profiles.';
COMMENT ON COLUMN kang.users.user_type IS 'User type such as member, admin, operator, or system.';
COMMENT ON COLUMN kang.users.auth_provider IS 'Primary auth provider such as firebase, local, google, apple, or facebook.';
COMMENT ON COLUMN kang.users.mfa_enabled IS 'Whether MFA is enabled.';
COMMENT ON COLUMN kang.users.locked_at IS 'Account lock timestamp.';
COMMENT ON COLUMN kang.users.is_active IS 'Operational active flag managed together with status.';
COMMENT ON COLUMN kang.users.created_by IS 'Internal user ID that created this user.';
COMMENT ON COLUMN kang.users.updated_by IS 'Internal user ID that last updated this user.';
COMMENT ON COLUMN kang.users.deleted_by IS 'Internal user ID that soft-deleted this user.';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_users_updated_at'
          AND tgrelid = 'kang.users'::regclass
    ) THEN
        CREATE TRIGGER trg_users_updated_at
        BEFORE UPDATE ON kang.users
        FOR EACH ROW
        EXECUTE PROCEDURE kang.touch_updated_at();
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS kang.user_profiles (
    user_id uuid NOT NULL,
    real_name_encrypted text,
    phone_encrypted text,
    phone_hash text,
    birth_date date,
    locale text DEFAULT 'ko-KR'::text NOT NULL,
    timezone text DEFAULT 'Asia/Seoul'::text NOT NULL,
    marketing_opt_in boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
    CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS kang.auth_identities (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    user_id uuid NOT NULL,
    provider text NOT NULL,
    provider_uid text NOT NULL,
    email text,
    email_verified boolean DEFAULT false NOT NULL,
    raw_claims jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT auth_identities_pkey PRIMARY KEY (id),
    CONSTRAINT auth_identities_provider_provider_uid_key UNIQUE (provider, provider_uid),
    CONSTRAINT auth_identities_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_auth_identities_user_id
    ON kang.auth_identities USING btree (user_id);

CREATE TABLE IF NOT EXISTS kang.roles (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS kang.user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    granted_by uuid,
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id)
        REFERENCES kang.roles(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_granted_by_fkey FOREIGN KEY (granted_by)
        REFERENCES kang.users(id)
);

CREATE TABLE IF NOT EXISTS kang.login_events (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    user_id uuid,
    firebase_uid text,
    provider text,
    success boolean NOT NULL,
    failure_reason text,
    ip_address inet,
    user_agent text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT login_events_pkey PRIMARY KEY (id),
    CONSTRAINT login_events_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_login_events_user_created
    ON kang.login_events USING btree (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS kang.user_devices (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    user_id uuid NOT NULL,
    platform text NOT NULL,
    device_id_hash text,
    push_token text,
    app_version text,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    revoked_at timestamp with time zone,
    CONSTRAINT user_devices_pkey PRIMARY KEY (id),
    CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_user_devices_user_id
    ON kang.user_devices USING btree (user_id);

CREATE TABLE IF NOT EXISTS kang.terms_versions (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    code text NOT NULL,
    title text NOT NULL,
    version text NOT NULL,
    body_url text,
    required boolean DEFAULT true NOT NULL,
    effective_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT terms_versions_pkey PRIMARY KEY (id),
    CONSTRAINT terms_versions_code_version_key UNIQUE (code, version)
);

CREATE TABLE IF NOT EXISTS kang.user_terms_agreements (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    user_id uuid NOT NULL,
    terms_version_id uuid NOT NULL,
    agreed boolean NOT NULL,
    ip_address inet,
    user_agent text,
    agreed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_terms_agreements_pkey PRIMARY KEY (id),
    CONSTRAINT user_terms_agreements_user_id_terms_version_id_key UNIQUE (user_id, terms_version_id),
    CONSTRAINT user_terms_agreements_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE CASCADE,
    CONSTRAINT user_terms_agreements_terms_version_id_fkey FOREIGN KEY (terms_version_id)
        REFERENCES kang.terms_versions(id)
);

CREATE TABLE IF NOT EXISTS kang.audit_events (
    id uuid DEFAULT kang.ms_generate_uuid() NOT NULL,
    user_id uuid,
    actor_user_id uuid,
    event_type text NOT NULL,
    entity_type text,
    entity_id uuid,
    ip_address inet,
    user_agent text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT audit_events_pkey PRIMARY KEY (id),
    CONSTRAINT audit_events_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES kang.users(id) ON DELETE SET NULL,
    CONSTRAINT audit_events_actor_user_id_fkey FOREIGN KEY (actor_user_id)
        REFERENCES kang.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_audit_events_user_created
    ON kang.audit_events USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_audit_events_entity
    ON kang.audit_events USING btree (entity_type, entity_id);

INSERT INTO kang.roles (code, name, description)
VALUES
    ('admin', 'Admin', 'Can manage users and application settings.'),
    ('member', 'Member', 'Standard application user.')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description;
